create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null check (role in ('patient', 'doctor', 'receptionist', 'admin')),
  remember_token text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  full_name text not null,
  cedula text not null unique,
  birth_date date,
  sex text,
  blood_type text,
  phone text,
  email text,
  address text,
  emergency_contact text,
  allergies jsonb,
  previous_conditions jsonb,
  current_medications jsonb,
  insurance_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint patients_cedula_length check (char_length(cedula) <= 20),
  constraint patients_sex_length check (sex is null or char_length(sex) <= 20),
  constraint patients_blood_type_length check (blood_type is null or char_length(blood_type) <= 10),
  constraint patients_phone_length check (phone is null or char_length(phone) <= 25)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  doctor_id bigint references public.users(id) on delete set null,
  specialty text not null,
  scheduled_at timestamptz not null,
  reason text not null,
  observations text,
  status text not null check (
    status in (
      'pending',
      'confirmed',
      'waiting',
      'in_consultation',
      'completed',
      'cancelled',
      'no_show'
    )
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete cascade,
  doctor_id bigint not null references public.users(id) on delete cascade,
  consultation_reason text not null,
  symptoms text,
  blood_pressure text,
  temperature numeric(4, 1),
  weight numeric(5, 2),
  height numeric(5, 2),
  diagnosis text not null,
  treatment text,
  recommendations text,
  next_control_at timestamptz,
  ai_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint medical_records_blood_pressure_length check (
    blood_pressure is null or char_length(blood_pressure) <= 50
  )
);

create table if not exists public.medical_documents (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  uploaded_by bigint not null references public.users(id) on delete cascade,
  title text not null,
  document_type text not null,
  file_path text,
  file_mime text,
  uploaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint medical_documents_document_type_length check (char_length(document_type) <= 100),
  constraint medical_documents_file_mime_length check (file_mime is null or char_length(file_mime) <= 120)
);

create table if not exists public.qr_tokens (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references public.appointments(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz,
  scanned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action text not null,
  input_payload jsonb,
  output_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_logs_action_length check (char_length(action) <= 120)
);

create table if not exists public.personal_access_tokens (
  id bigint generated by default as identity primary key,
  tokenable_type text not null,
  tokenable_id bigint not null,
  name text not null,
  token text not null unique,
  abilities text,
  last_used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists patients_user_id_idx on public.patients(user_id);
create index if not exists appointments_patient_id_idx on public.appointments(patient_id);
create index if not exists appointments_doctor_id_idx on public.appointments(doctor_id);
create index if not exists appointments_scheduled_at_idx on public.appointments(scheduled_at);
create index if not exists appointments_status_idx on public.appointments(status);
create index if not exists medical_records_appointment_id_idx on public.medical_records(appointment_id);
create index if not exists medical_records_patient_id_idx on public.medical_records(patient_id);
create index if not exists medical_records_doctor_id_idx on public.medical_records(doctor_id);
create index if not exists medical_documents_patient_id_idx on public.medical_documents(patient_id);
create index if not exists medical_documents_uploaded_by_idx on public.medical_documents(uploaded_by);
create index if not exists ai_logs_user_id_idx on public.ai_logs(user_id);
create index if not exists personal_access_tokens_tokenable_idx
  on public.personal_access_tokens(tokenable_type, tokenable_id);
create index if not exists personal_access_tokens_expires_at_idx
  on public.personal_access_tokens(expires_at);

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists set_patients_updated_at on public.patients;
create trigger set_patients_updated_at
before update on public.patients
for each row execute function public.set_updated_at();

drop trigger if exists set_appointments_updated_at on public.appointments;
create trigger set_appointments_updated_at
before update on public.appointments
for each row execute function public.set_updated_at();

drop trigger if exists set_medical_records_updated_at on public.medical_records;
create trigger set_medical_records_updated_at
before update on public.medical_records
for each row execute function public.set_updated_at();

drop trigger if exists set_medical_documents_updated_at on public.medical_documents;
create trigger set_medical_documents_updated_at
before update on public.medical_documents
for each row execute function public.set_updated_at();

drop trigger if exists set_qr_tokens_updated_at on public.qr_tokens;
create trigger set_qr_tokens_updated_at
before update on public.qr_tokens
for each row execute function public.set_updated_at();

drop trigger if exists set_ai_logs_updated_at on public.ai_logs;
create trigger set_ai_logs_updated_at
before update on public.ai_logs
for each row execute function public.set_updated_at();

drop trigger if exists set_personal_access_tokens_updated_at on public.personal_access_tokens;
create trigger set_personal_access_tokens_updated_at
before update on public.personal_access_tokens
for each row execute function public.set_updated_at();
